Dramos/merge branches
ecomappah/Back-End-Ecomapper-Capstone-Project pull request #2
Opened 2022-11-29 19:48 UTC by daliaramos

I merged the branches, deleted the node_modules, and added gitignore file.

2022-11-29 23:54 UTC, jgmccarthy7 requested changes
It looks like the two branches got put together and both apps are still separated. The desired behavior is that we have one app that can direct to the different pages you all worked on. Please work with Landstrom to port over the page he made and remove any unneeded code.

2022-11-29 23:54 UTC, jgmccarthy7 commented on README.md
> +Ian G (guyian@pdx.edu)
All the back end devs should be here, instead of just Ian.

2022-11-29 23:54 UTC, jgmccarthy7 commented on app.js
> +app.use('/', indexRouter);
Did you work with Landstrom to port over the work he did onto Ian's index.js? It looks like both app.js and index.js are two separate Node apps as opposed to one app with all the pages.

2022-11-29 23:54 UTC, jgmccarthy7 commented on index.js
> +const express = require("express");
I think this is a separate app from app.js - which should stay?

2022-11-29 23:55 UTC, jgmccarthy7 commented
While I am happy to look at pull requests, it's better if you ask for the other members of your team for review of the code - Dan and I will not be as knowledgeable on the code and behavior as your team.

2022-11-30 01:54 UTC, jgmccarthy7 approved these changes
Looks good to me!

2022-11-30 01:54 UTC, jac0bml approved these changes
Addressed in Zoom call with @jgmccarthy7 @daliaramos

2022-12-02 06:16 UTC, merged